export const SET_USER = 'SET_USER';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const SET_CONNECT_SOCKET = 'SET_CONNECT_SOCKET';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_REFRESH_TOKEN = 'SET_REFRESH_TOKEN';
export const SET_SERVER_STATUS = 'SET_SERVER_STATUS';
export const SET_SERVER_ERROR = 'SET_SERVER_ERROR';